#!/bin/bash
set -e

. config

cd corefx
if [ ! -d "packages/NETStandard.Library" ]; then
  ./run.sh sync
fi
ROOTFS_DIR=$ROOTFS_DIR ./run.sh build-native -buildArch=$ARCH -os=$OS_NAME -SkipTests -$BUILD_CONFIG -- cross
ROOTFS_DIR=$ROOTFS_DIR ./run.sh build-managed -buildArch=$ARCH -os=$OS_NAME -SkipTests -ConfigurationGroup=$BUILD_CONFIG -runtimeos=$OS_NAME
cd ..
