#!/bin/bash
set -e

. config

cd coreclr
grep "Microsoft.NETCore.Runtime.CoreCLR" ../core-setup/pkg/projects/Microsoft.NETCore.App/project.json.template > version.txt
BUILD_NUMBER_MAJOR=$(cat version.txt | sed 's/.*-beta-//' | sed 's/-.*//')
BUILD_NUMBER_MINOR=$(cat version.txt | sed 's/.*-beta-.*-//' | sed 's/".*//')
sed -i 's/\-O[23]/-O1/' src/pal/tools/clang-compiler-override.txt
ROOTFS_DIR=$ROOTFS_DIR BuildNumberMajor=$BUILD_NUMBER_MAJOR BuildNumberMinor=$BUILD_NUMBER_MINOR ./build.sh $ARCH $BUILD_CONFIG cross skiptests
cd ..

mkdir -p packages
cp -v coreclr/bin/Product/$OS_NAME.$ARCH.$BUILD_CONFIG/.nuget/pkg/*.nupkg packages
