#!/bin/bash
set -e

. config

cd core-setup
cd src/corehost
./build.sh --arch arm --rid ubuntu.16.04-arm --hostver $VERSION --fxrver $VERSION --policyver $VERSION --commithash $VERSION --xcompiler /usr/bin/arm-linux-gnueabihf-g++
cd ../..
cd ..

cd coreclr
ROOTFS_DIR=$ROOTFS_DIR ./build.sh $ARCH $BUILD_CONFIG cross skiptests
cd ..

cd corefx
ROOTFS_DIR=$ROOTFS_DIR ./run.sh build-native -buildArch=$ARCH -$BUILD_CONFIG -os=$OS_NAME -SkipTests -- cross
./run.sh build-managed -os=$OS_NAME -target-os=$OS_NAME -buildArch=$ARCH -debug -binaries
./run.sh build-managed -ProducesTarget | grep "^  " | sed 's/^  //' > bin/packages.txt
cd ..

cd cli
#./build.sh
#cd bin
#cp
#cd ..
cd ..

cd libuv
./autogen.sh
./configure --host=arm-linux-gnueabihf
make
cd ..
