#!/bin/bash
set -e

. config
rm -rf $OUT_ROOT

mkdir -p $HOST_OUT
mkdir -p $SHARED_OUT
sudo mkdir -p $ROOTFS_DIR/dotnet-arm/

cp -v Microsoft.NETCore.App.deps.json $SHARED_OUT
git -C core-setup rev-parse HEAD > $SHARED_OUT/.version
echo $VERSION >> $SHARED_OUT/.version

cd libuv
cp -v .libs/libuv.so $SHARED_OUT
cd ..

cd core-setup
cd resources
cp -v LICENSE.txt ThirdPartyNotices.txt $OUT_ROOT
cd ..
cd src/corehost/cli
cp -v exe/dotnet $OUT_ROOT
cp -v exe/dotnet $SHARED_OUT
cp -v exe/dotnet $SHARED_OUT/corehost
cp -v dll/libhostpolicy.so $SHARED_OUT
cp -v fxr/libhostfxr.so $HOST_OUT
cp -v fxr/libhostfxr.so $SHARED_OUT
cd ../../..
cd ..

cd coreclr
cd bin/Product/$OS_NAME.$ARCH.$BUILD_CONFIG
cp -v libclrjit.so libcoreclr.so libdbgshim.so libmscordaccore.so libmscordbi.so libsosplugin.so libsos.so mscorlib.dll mscorlib.ni.dll SOS.NETCore.dll sosdocsunix.txt System.Globalization.Native.so System.Private.CoreLib.dll System.Private.CoreLib.ni.dll $SHARED_OUT
cd ../../..
cd ..

cd corefx
cd bin/$OS_NAME.$ARCH.$BUILD_CONFIG
cp -v Native/*.a Native/*.so $SHARED_OUT
cd ..
cat ../../packages.txt | xargs -I % sh -c "find * -name %.dll | grep ^[LUA].*/%/%.dll$" | xargs -I % cp -v % $SHARED_OUT
cd ..
cd ..

cd roslyn
cd Binaries/$BUILD_CONFIG
cp -v Microsoft.CodeAnalysis.dll Microsoft.CodeAnalysis.CSharp.dll Microsoft.CodeAnalysis.VisualBasic.dll $SHARED_OUT
cd ../..
cd ..

cd cli
#./build.sh
#cd bin
#cp
#cd ..
cd ..
