#!/bin/bash
set -e

. config

mkdir -p $HOST_OUT
mkdir -p $SHARED_OUT

cd core-setup
cd resources
cp -v LICENSE.txt ThirdPartyNotices.txt $OUT_ROOT
cd ..
cd src/corehost/cli
cp -v exe/dotnet $OUT_ROOT
cp -v exe/dotnet $SHARED_OUT
cp -v exe/dotnet $SHARED_OUT/corehost
cp -v dll/libhostpolicy.so $SHARED_OUT
cp -v fxr/libhostfxr.so $HOST_OUT
cd ../../..
cd ..

cd coreclr
cd bin/Product/$OS_NAME.$ARCH.$BUILD_CONFIG
cp *.so *.dll $SHARED_OUT
cd ../../..
cd ..

cd corefx
cp bin/Linux.arm.Debug/Native/*.so $SHARED_OUT
cd ..

cd cli
#./build.sh
#cd bin
#cp
#cd ..
cd ..

cd libuv
cp -v .libs/libuv.so $SHARED_OUT
cd ..
