#!/bin/bash
set -e

cd libuv
git clean -fdx
git reset --hard
cd ..

cd core-setup
git clean -fdx
git reset --hard
cd ..

cd coreclr
git clean -fdx
git reset --hard
cd ..

cd corefx
git clean -fdx
git reset --hard
cd ..

cd roslyn
git clean -fdx
git reset --hard
cd ..

cd cli
git clean -fdx
git reset --hard
cd ..
