#!/bin/bash
set -e

. config

sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev qemu qemu-user-static binfmt-support debootstrap binutils-arm-linux-gnueabihf clang-3.6 llvm-3.6 g++-arm-linux-gnueabihf gyp

if [ ! -d "libuv" ]; then
  git clone git@github.com:libuv/libuv
fi

if [ ! -d "core-setup" ]; then
  git clone git@github.com:dotnet/core-setup
fi

if [ ! -d "coreclr" ]; then
  git clone git@github.com:dotnet/coreclr
fi

if [ ! -d "corefx" ]; then
  git clone git@github.com:dotnet/corefx
fi

if [ ! -d "cli" ]; then
  git clone git@github.com:dotnet/cli
fi

if [ ! -d "$ROOTFS_DIR" ]; then
  sudo ROOTFS_DIR=$ROOTFS_DIR coreclr/cross/build-rootfs.sh arm $ROOTFS_BRANCH
fi
sudo chroot $ROOTFS_DIR apt-get install build-essential symlinks gettext libcurl4-openssl-dev libicu-dev libkrb5-dev liblttng-ust-dev libssl-dev libunwind8-dev zlib1g-dev
