#!/bin/bash
set -e

. config

sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y install cmake llvm-3.8 clang-3.8 lldb-3.8 lldb-3.8-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev qemu qemu-user-static binfmt-support debootstrap binutils-arm-linux-gnueabihf clang-3.8 llvm-3.8 g++-arm-linux-gnueabihf gyp unzip libtool automake devscripts debhelper

if [ ! -f "libicu52_52.1-8_amd64.deb" ]; then
  wget http://launchpadlibrarian.net/201330288/libicu52_52.1-8_amd64.deb
fi
sudo dpkg -i libicu52_52.1-8_amd64.deb

if [ ! -d "libuv" ]; then
  git clone https://github.com/libuv/libuv
else
  git -C libuv pull
fi

if [ ! -d "coreclr" ]; then
  git clone https://github.com/dotnet/coreclr
else
  git -C coreclr pull
fi

if [ ! -d "corefx" ]; then
  git clone https://github.com/dotnet/corefx
else
  git -C corefx pull
fi

if [ ! -d "sdk" ]; then
  git clone https://github.com/dotnet/sdk
else
  git -C sdk pull
fi

if [ ! -d "roslyn" ]; then
  git clone https://github.com/dotnet/roslyn
else
  git -C roslyn pull
fi

if [ ! -d "core-setup" ]; then
  git clone https://github.com/dotnet/core-setup
else
  git -C core-setup pull
fi

if [ ! -d "cli" ]; then
  git clone https://github.com/dotnet/cli
  git -C cli remote add qmfrederik https://github.com/qmfrederik/cli
  git -C cli fetch qmfrederik
  git -C cli cherry-pick 14d8f808fc74181a8ec38c4173c0ccf74f2f6bc9
else
  git -C cli pull
fi

if [ ! -d "$ROOTFS_DIR" ]; then
  sudo ROOTFS_DIR=$ROOTFS_DIR coreclr/cross/build-rootfs.sh arm $ROOTFS_BRANCH
fi
sudo chroot $ROOTFS_DIR apt-get -y update
sudo chroot $ROOTFS_DIR apt-get -y dist-upgrade
sudo chroot $ROOTFS_DIR apt-get -y install bash-completion build-essential symlinks gettext libcurl4-openssl-dev libicu-dev libkrb5-dev liblttng-ust-dev libssl-dev libunwind8-dev zlib1g-dev
sudo chroot $ROOTFS_DIR symlinks -cr /usr
