#!/bin/bash
set -e

. config

sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get -y install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev qemu qemu-user-static binfmt-support debootstrap binutils-arm-linux-gnueabihf clang-3.6 llvm-3.6 g++-arm-linux-gnueabihf

if [ ! -d core-setup ]; then
  git clone git@github.com:dotnet/core-setup
fi

if [ ! -d coreclr ]; then
  git clone git@github.com:dotnet/coreclr
fi

if [ ! -d corefx ]; then
  git clone git@github.com:dotnet/corefx
fi

if [ ! -d cli ]; then
  git clone git@github.com:dotnet/cli
fi

if [ ! -d libuv ]; then
  git clone git@github.com:libuv/libuv
fi

cd core-setup
git checkout $COREHOST_BRANCH
git pull
cd ..

cd coreclr
git checkout $CORECLR_BRANCH
git pull
cd ..

cd corefx
git checkout $COREFX_BRANCH
git pull
cd ..

cd cli
git checkout $CLI_BRANCH
git pull
cd ..

cd libuv
git checkout $LIBUV_BRANCH
git pull
cd ..

if [ ! -d "$ROOTFS_DIR" ]; then
  sudo ROOTFS_DIR=$ROOTFS_DIR coreclr/cross/build-rootfs.sh arm $ROOTFS_BRANCH
fi
