#!/bin/bash
set -e

. config

cd libuv
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $LIBUV_BRANCH || true
git pull || true
git rebase || true
cd ..

cd coreclr
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $CORECLR_BRANCH || true
git pull || true
git rebase || true
cd ..

cd corefx
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $COREFX_BRANCH || true
git pull || true
git rebase || true
cd ..

cd sdk
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $SDK_BRANCH || true
git pull || true
git rebase || true
cd ..

cd roslyn
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $ROSLYN_BRANCH || true
git pull || true
git rebase || true
cd ..

cd core-setup
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $COREHOST_BRANCH || true
git pull || true
git rebase || true
cd ..

cd cli
git fetch --tags
git reset --hard
git checkout -- * || true
git checkout $CLI_BRANCH || true
git pull || true
git rebase || true
cd ..
